<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
/** @var \Magento\Wishlist\ViewModel\AllowedQuantity $viewModel */
$viewModel = $block->getData('allowedQuantityViewModel');
$allowedQty = $viewModel->setItem($item)->getMinMaxQty();
$config=$block->getData('productviewModel');
$Pricinghelper = $config->getPriceHelper();
$configenable = $config->enable();
$maxqty=$config->maxqty();
$dropdowntype=$config->dropdowntype();
$customvalue=$config->customvalue();
$showpricedropdown=$config->showpricedropdown();
$startqty=$config->startqty();
$incrementqty=$config->incrementqty();
if ($showpricedropdown=='price-per-one') {
        $pricetext='for each';
} elseif ($showpricedropdown=='total-price') {
    $pricetext='for total';
} else {
    $pricetext='';
}
$customprice=$product->getFinalPrice();
?>
<?php foreach ($block->getChildNames() as $childName): ?>
    <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
<?php endforeach;?>
<div class="box-tocart">
    <fieldset class="fieldset">
    <?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility()): ?>
        <?php if (($product->getTypeId()=='simple' || $product->getTypeId()=='configurable')
         && ($configenable == 1)) { ?>     
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <?php if ($dropdowntype=='0') { ?>
            <div class="control">
                <select name="qty[<?= $block->escapeHtml($item->getId()) ?>]" 
                    title="<?= $block->escapeHtml(__('Qty')) ?>" class="input-text qty">
                    <?php for ($i=1; $i <= $maxqty; $i++):?>
                        <?php $price=$customprice*$i;
                        $Totalprice=$Pricinghelper->currency($price, true, false);
                        $peritemprice=$Pricinghelper->currency($customprice, true, false); ?>
                        <option value="<?= $block->escapeHtml($i)?>" <?= ($item->getQty() == $i) ? ' selected' : '' ?>>
                            <?php if ($pricetext=='for each') { echo $block->escapeHtml($i).
                                ' '.$block->escapeHtml($pricetext).' '.$block->escapeHtml($peritemprice);
                            } elseif ($pricetext=='for total') { echo $block->escapeHtml($i).
                                ' '.$block->escapeHtml($pricetext).' '.$block->escapeHtml($Totalprice);
                            } else { echo $block->escapeHtml($i);}?>
                        </option>
                    <?php endfor;?>
                </select>
            </div>
             <?php } elseif ($dropdowntype=='1') { ?>
             <div class="control">
                <select name="qty[<?= $block->escapeHtml($item->getId()) ?>]" 
                    title="<?= $block->escapeHtml(__('Qty')) ?>" class="input-text qty">
                    <?php for ($i=$startqty; $i <= $maxqty; $i+=$incrementqty):?>
                        <?php $price=$customprice*$i;
                        $Totalprice=$Pricinghelper->currency($price, true, false);
                        $peritemprice=$Pricinghelper->currency($customprice, true, false); ?>
                        <option value="<?= $block->escapeHtml($i)?>" <?= ($item->getQty() == $i) ? ' selected' : '' ?>>
                            <?php if ($pricetext=='for each') { echo $block->escapeHtml($i).
                                ' '.$block->escapeHtml($pricetext).' '.$block->escapeHtml($peritemprice);
                            } elseif ($pricetext=='for total') { echo $block->escapeHtml($i).
                                ' '.$block->escapeHtml($pricetext).' '.$block->escapeHtml($Totalprice);
                            } else { echo $block->escapeHtml($i);}?>
                        </option>
                    <?php endfor;?>
                </select>
            </div>   
            <?php } else { ?>
             <div class="control">
                 <select name="qty[<?= $block->escapeHtml($item->getId()) ?>]" 
                    title="<?= $block->escapeHtml(__('Qty')) ?>" class="input-text qty">
                    <?php $customvalues = explode(",", $customvalue);
                    foreach ($customvalues as $customval) {
                        $price=$customprice*$customval;
                        $Totalprice=$Pricinghelper->currency($price, true, false);
                        $peritemprice=$Pricinghelper->currency($customprice, true, false);
                        ?>
                        <option value="<?= $block->escapeHtml($customval)?>"
                         <?= ($item->getQty() == $customval) ? ' selected' : '' ?>>
                            <?php if ($pricetext=='for each') { echo $block->escapeHtml($customval).
                                ' '.$block->escapeHtml($pricetext).' '.$block->escapeHtml($peritemprice);
                            } elseif ($pricetext=='for total') { echo $block->escapeHtml($customval).
                                ' '.$block->escapeHtml($pricetext).' '.$block->escapeHtml($Totalprice);
                            } else { echo $block->escapeHtml($customval);}?>
                        </option>
                    <?php } ?>
                </select>
             </div>   
            <?php } ?>    
        </div>  
        <?php } else { ?>
        <div class="field qty">
            <label class="label" for="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]">
                <span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number" data-role="qty" id="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]"
                 class="input-text qty" data-validate="{'required-number':true,'validate-greater-than-zero':true,
                  'validate-item-quantity':{'minAllowed':<?= /* @noEscape */ $allowedQty['minAllowed'] ?>,
                  'maxAllowed':<?= /* @noEscape */ $allowedQty['maxAllowed'] ?>}}"
               name="qty[<?= $block->escapeHtmlAttr($item->getId()) ?>]" value="<?= /* @noEscape */
                $block->getAddToCartQty($item) * 1 ?>" <?= $product->isSaleable() ? '' : 'disabled="disabled"' ?>>
            </div>
        </div>
         <?php } ?>
    <?php endif; ?>
    <?php if ($product->isSaleable()): ?>
    <div class="product-item-actions">
        <div class="actions-primary">
            <button type="button" data-role="tocart" data-post='<?= /* @noEscape */
            $block->getItemAddToCartParams($item) ?>' 
                title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" data-item-id="<?=
                $block->escapeHtmlAttr($item->getId()) ?>" class="action tocart primary">
                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
            </button>
        </div>
    </div>
    <?php else: ?>
        <?php if ($product->getIsSalable()): ?>
            <p class="available stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                <span><?= $block->escapeHtml(__('In stock')) ?></span>
            </p>
        <?php else: ?>
            <p class="unavailable stock" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
            </p>
        <?php endif; ?>
    <?php endif; ?>
    </fieldset>
</div>
