<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$config=$block->getData('productviewModel');
$Pricinghelper = $config->getPriceHelper();
$configenable = $config->enable();
$maxqty=$config->maxqty();
$dropdowntype=$config->dropdowntype();
$customvalue=$config->customvalue();
$showpricedropdown=$config->showpricedropdown();
$startqty=$config->startqty();
$incrementqty=$config->incrementqty();
if ($showpricedropdown=='price-per-one') {
        $pricetext='for each';
} elseif ($showpricedropdown=='total-price') {
    $pricetext='for total';
} else {
    $pricetext='';
}
$customprice=$product->getFinalPrice();
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()): ?>
                <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else: ?>
                <span class="product-item-photo">
            <?php endif; ?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()): ?>
                </a>
            <?php else: ?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()): ?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else: ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()): ?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option): ?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                        <?= $block->escapeHtml($_formatedOptionValue['full_view'], ['span', 'a']) ?>
                                    <?php else: ?>
                                        <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif; ?>
                <?php if ($messages = $block->getMessages()): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock): ?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif; ?>
            </div>
        </td>

        <?php if ($canApplyMsrp): ?>
            <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "origin": "info",
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
            </td>
        <?php else: ?>
            <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td>
        <?php endif; ?>
        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
            <div class="field qty">
            <?php if (($product->getTypeId()=='simple' || $product->getTypeId()=='configurable')
            && ($configenable == 1)) { ?>     
        <div class="control qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                                         <?php if ($dropdowntype=='0') { ?>
            <div class="control">
                <select name="qty" id="qty" class="qty" data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>">
                                                <?php for ($i=1; $i <= $maxqty; $i++):?>
                                                    <?php $price=$customprice*$i;
                                                    $Totalprice=$Pricinghelper->currency($price, true, false);
                                                    $peritemprice=$Pricinghelper->currency($customprice, true, false); ?>
                        <option value="<?= $block->escapeHtml($i)?>">
                                                    <?php if ($pricetext=='for each') { echo $block->escapeHtml($i).
                                                        ' '.$block->escapeHtml($pricetext).' '.$block->escapeHtml($peritemprice);
                                                    } elseif ($pricetext=='for total') { echo $block->escapeHtml($i).
                                                        ' '.$block->escapeHtml($pricetext).' '.$block->escapeHtml($Totalprice);
                                                    } else { echo $block->escapeHtml($i);}?>
                        </option>
                    <?php endfor;?>
                </select>
            </div>
             <?php } elseif ($dropdowntype=='1') { ?>
             <div class="control">
                <select id="cart-<?= /* @escapeNotVerified */ $block->escapeHtml($_item->getId()) ?>-qty"
                    name="cart[<?= /* @escapeNotVerified */ $block->escapeHtml($_item->getId()) ?>][qty]"
                    data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                    data-role="cart-item-qty"
                    class="qty select_<?= $block->escapeHtml($_item->getId())?>">
                                             <?php for ($i=$startqty; $i <= $maxqty; $i+=$incrementqty):?>
                                                    <?php $price=$customprice*$i;
                                                    $Totalprice=$Pricinghelper->currency($price, true, false);
                                                    $peritemprice=$Pricinghelper->currency($customprice, true, false); ?>
                        <option value="<?= $block->escapeHtml($i) ?>" <?=($i==$block->getQty())?'selected':'';?>>
                                                    <?php if ($pricetext=='for each') { echo $block->escapeHtml($i).
                                                        ' '.$block->escapeHtml($pricetext).' '.$block->escapeHtml($peritemprice);
                                                    } elseif ($pricetext=='for total') { echo $block->escapeHtml($i).
                                                        ' '.$block->escapeHtml($pricetext).' '.$block->escapeHtml($Totalprice);
                                                    } else { echo $block->escapeHtml($i);}?>
                        </option>
                    <?php endfor;?>
                </select>
            </div>     
            <?php } else { ?>
             <div class="control">
                 <select id="cart-<?= /* @escapeNotVerified */ $block->escapeHtml($_item->getId()) ?>-qty"
                    name="cart[<?= /* @escapeNotVerified */ $block->escapeHtml($_item->getId()) ?>][qty]"
                    data-cart-item-id="<?= $block->escapeHtml($_item->getSku()) ?>"
                    data-role="cart-item-qty"
                    class="qty select_<?= $block->escapeHtml($_item->getId())?>">
                    <?php $customvalues = explode(",", $customvalue);
                    foreach ($customvalues as $customval) {
                        $price=$customprice*$customval;
                        $Totalprice=$Pricinghelper->currency($price, true, false);
                        $peritemprice=$Pricinghelper->currency($customprice, true, false);
                        ?>
                        <option value="<?= $block->escapeHtml($customval)?>" <?=($customval==$block->getQty())?'selected':'';?>>
                            <?php if ($pricetext=='for each') { echo $block->escapeHtml($customval).
                                ' '.$block->escapeHtml($pricetext).' '.$block->escapeHtml($peritemprice);
                            } elseif ($pricetext=='for total') { echo $block->escapeHtml($customval).
                                ' '.$block->escapeHtml($pricetext).' '.$block->escapeHtml($Totalprice);
                            } else { echo $block->escapeHtml($customval);}?>
                        </option>
                    <?php } ?>
                </select>
             </div>   
            <?php } ?>    
        </div>  
        <?php } else { ?>  
                <div class="control qty">
                    <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                        <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                        <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                               name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                               data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                               value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                               type="number"
                               size="4"
                               step="any"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="{required:true,'validate-greater-than-zero':true}"
                               data-item-qty="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                               data-role="cart-item-qty"/>
                    </label>
                </div>
            <?php } ?>
            </div>
        </td>

        <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp): ?>
                <span class="cart msrp subtotal">--</span>
            <?php else: ?>
                <?= $block->getRowTotalHtml($_item) ?>
            <?php endif; ?>
        </td>
    </tr>
    <tr class="item-actions">
        <td colspan="4">
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
</tbody>
